- name: "easy-pick"
  color: "bcf5db"
- name: "wontfix"
  color: "eeeeee"

- name: "prio:critical"
  color: "FE0000"
- name: "prio:high"
  color: "FFC000"
- name: "prio:low"
  color: "01B0F1"
- name: "prio:medium"
  color: "FFFF02"


