- name: "easy-pick"
  color: "bcf5db"
- name: "wontfix"
  color: "ffffff"

- name: "prio:critical"
  color: "FE0000"
- name: "prio:high"
  color: "FFC000"
- name: "prio:low"
  color: "01B0F1"
- name: "prio:medium"
  color: "FFFF02"


- name: "scope:pre-production"
  color: "efefef"
- name: "scope:auth"
  color: "efefef"
- name: "scope:authz"
  color: "efefef"
- name: "scope:ability"
  color: "efefef"

