name: Manage Labels

on: [push]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Manage labels
        uses: julbme/gh-action-manage-label@v1
        with:
          from: |
            src/default.yaml
            src/autofix.yaml
            src/types.yaml
            src/scopes.yaml
          skip_delete: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
