name: Manage Labels

on: [push]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Manage labels
        uses: julbme/gh-action-manage-label@v1
        with:
          from: src/autofix.yaml
          skip_delete: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
